apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: contactqueue
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://rabbitmq:5672"
  - name: queueName
    value: contactqueue