version: '3.4'

services:
  contactsmanager:
    image: ${DOCKER_REGISTRY-}contactsmanager
    build:
      context: .
      dockerfile: ContactsManager/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
       - rabbitmq
    networks:
      - cantacts-dapr-network

  manager-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
        "-app-id", "ContactManager", 
        "-app-port", "80",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yml",
        "-log-level", "debug"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - contactsmanager
      - rabbitmq
    network_mode: "service:contactsmanager"
   
  contactsaccessor:
    image: ${DOCKER_REGISTRY-}contactsaccessor
    build:
      context: .
      dockerfile: ContactsAccessor/Dockerfile
    depends_on:
        - rabbitmq
    networks:
      - cantacts-dapr-network

  accessor-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
        "-app-id", "ContactsAccessor", 
        "-app-port", "80",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yml",
        "-log-level", "debug"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - contactsaccessor
      - rabbitmq
    network_mode: "service:contactsaccessor"

  mongodb:
    image: mongo
    ports:
      - 27018:27017
    networks:
      - cantacts-dapr-network

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cantacts-dapr-network 

networks:
   cantacts-dapr-network: 